# Generated by Django 3.0.3 on 2020-10-30 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_auto_20201028_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
